// recipe_app_react/src/app/login/page.tsx
'use client';
import React, { ChangeEvent, useContext, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ErrorResponse, LoginData } from '@/types';
import { useUserContext } from '@/components/AppState';
import { useServices } from '@/components/ServiceContext';


export default function Login() {
    const router = useRouter();
    const [validationError, setValidationError] = useState<ErrorResponse>({ message: '' });
    const [formData, setFormData] = useState<LoginData>({
        usernameOrEmail: '',
        password: ''
    });
    const { userContext, setUserContext } = useUserContext();
    const { accountService } = useServices();
    
    const updateInput = (e: ChangeEvent<HTMLInputElement>) => {
        setFormData({...formData, [e.target.name]: e.target.value});
        setValidationError({ message: '' });
    }
    
    const login = async (e: React.MouseEvent<HTMLButtonElement>) => {
        e.preventDefault();
        
        if (formData.usernameOrEmail.length < 5 || formData.password.length < 6) {
            setValidationError({ message: 'Invalid input lengths' });
            return;
        }

        const response = await accountService.login(formData);
        if (response.data) {
            setUserContext({...userContext, jsonWebToken: response.data.jsonWebToken, refreshToken: response.data.refreshToken});
            router.push("/");
        }

        if (response.errors && response.errors.length > 0) {
            setValidationError(response.errors[0]);
        }
    }
    
    return (
        <div className="row">
            <div className="col-md-5">
                <h2>Log in</h2>
                <hr/>
                <div className="text-danger" role="alert">{validationError.message}</div>
                <div className="form-floating mb-3">
                    <input id="usernameOrEmail" type="username" className="form-control" autoComplete="username"
                           name="usernameOrEmail"
                           value={formData.usernameOrEmail} placeholder="name@example.com" onChange={updateInput}/>
                    <label htmlFor="usernameOrEmail" className="form-label">Username or email</label>
                </div>
                <div className="form-floating mb-3">
                    <input id="password" type="password" className="form-control" autoComplete="password"
                           name="password"
                           value={formData.password} placeholder="password" onChange={updateInput}/>
                    <label htmlFor="password" className="form-label">Password</label>
                </div>
                <div>
                    <button className="w-100 btn btn-lg btn-primary" onClick={login} type="submit">Log in</button>
                </div>
            </div>
        </div>
    );
}

// recipe_app_vue/src/views/account/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAuthStore } from '@/stores/auth';
import type { LoginData, ResultObject, UserInfo } from '@/types';
import { useRoute, useRouter } from 'vue-router';
import useServices from '@/helpers/useServices';

const { accountService } = useServices();

const loginData = ref<LoginData>({
    usernameOrEmail: '',
    password: ''
});
const loginIsOngoing = ref(false);
const errors = ref<string[]>([]);

const authStore = useAuthStore();
const router = useRouter();
const route = useRoute();
const returnUrl = route.query.returnUrl as string | undefined;

const submitLogin = async () => {
    loginIsOngoing.value = true;

    const result: ResultObject<UserInfo> = await accountService.login(loginData.value);

    if (result.data) {
        authStore.jsonWebToken = result.data.jsonWebToken;
        authStore.refreshToken = result.data.refreshToken;
        errors.value = [];
        await router.push(returnUrl ?? '/');
    } else {
        errors.value = result.errors?.map(e => e.message) ?? [];
    }

    loginIsOngoing.value = false;
};
</script>

<template>
    <h1 v-if="!authStore.isAuthenticated">Log in</h1>
    <div class="row">
        <div class="col-md-6">
            <div v-if="!authStore.isAuthenticated">
                <form method="post">
                    <hr />
                    <div class="text-danger">{{ errors.join('\n') }}</div>
                    <div class="form-floating mb-3">
                        <input v-model="loginData.usernameOrEmail" class="form-control" autocomplete="username"
                               placeholder=""
                               type="text"
                               id="Input_UsernameOrEmail"
                               name="Input.UsernameOrEmail">
                        <label class="form-label" for="Input_UsernameOrEmail">Username or email</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input v-model="loginData.password" class="form-control" autocomplete="current-password"
                               placeholder="" type="password" id="Input_Password"
                               name="Input.Password">
                        <label class="form-label" for="Input_Password">Password</label>
                    </div>
                    <div>
                        <button @click="submitLogin" :disabled="loginIsOngoing" id="login-submit" type="submit"
                                class="w-100 btn btn-lg btn-primary">
                            <span v-if="loginIsOngoing">
                                <span class="spinner-border spinner-border-sm" role="status"></span>
                                Loading...
                            </span>
                            <span v-else>Log in</span>
                        </button>
                        <p>Don't have an account?
                            <RouterLink :to="{name: 'Register', query: route.query}">Register</RouterLink>
                        </p>
                    </div>
                </form>
            </div>
            <span v-else>You're already logged in!</span>
        </div>
    </div>
</template>

<style scoped>

</style>
