// frontend/exam_webapp_vue/src/views/samples/Samples.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import type { Sample } from '@/types';
import useServices from '@/helpers/useServices';

const { samplesService } = useServices();
const samples = ref<Sample[]>([]);

onMounted(async () => {
    const result = await samplesService.findAll();
    samples.value = result.data!;
});
</script>

<template>
    <h1>Samples</h1>
    <p>
        <RouterLink :to="{name: 'SampleCreate'}">Create New</RouterLink>
    </p>
    <table v-if="samples.length" class="table">
        <thead>
        <tr>
            <th>
                Field
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="sample in samples" :key="sample.id">
            <td>
                {{ sample.field }}
            </td>
            <td>
                <RouterLink :to="{name: 'SampleEdit', params: {id: sample.id}}">Edit</RouterLink>
                |
                <RouterLink :to="{name: 'SampleDetails', params: {id: sample.id}}">Details</RouterLink>
                |
                <RouterLink :to="{name: 'SampleDelete', params: {id: sample.id}}">Delete</RouterLink>
            </td>
        </tr>
        </tbody>
    </table>
    <span v-else>Loading...</span>
</template>

<style scoped></style>

// exam_webapp_react/src/app/samples/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useServices } from '@/components/ServiceContext';
import { Sample } from '@/types';
import Link from 'next/link';

export default function Samples() {
    const [isLoading, setIsLoading] = useState(true);
    const [samples, setSamples] = useState<Sample[]>([]);
    const { samplesService } = useServices();

    const loadSamples = async () => {
        const allSamples = await samplesService.findAll();
        if (allSamples.data) {
            setSamples(allSamples.data);
        }
        setIsLoading(false);
    };

    useEffect(() => {
        loadSamples().then();
    }, []);
    
    return (
        <>
            <h1>Index</h1>

            <p>
                <Link href={'/samples/create'}>Create New</Link>
            </p>
            {(isLoading)
                ? <p>Loading...</p>
                : renderSamplesTable(samples)}
        </>
    );
}

function renderSamplesTable(samples: Sample[]) {
    return <table className="table">
        <thead>
        <tr>
            <th>
                Field
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {renderSamples(samples)}
        </tbody>
    </table>;
}

function renderSamples(samples: Sample[]) {
    return samples.map(sample => (
        <tr key={sample.id}>
            <td>
                {sample.field}
            </td>
            <td>
                <Link href={`/samples/${sample.id}/edit`}>Edit</Link> |
                <Link href={`/samples/${sample.id}`}>Details</Link> |
                <Link href={`/samples/${sample.id}/delete`}>Delete</Link>
            </td>
        </tr>
    ));
}
