// exam_webapp_vue/src/components/Header.vue
<script setup lang="ts">
import { useAuthStore } from '@/stores/auth';
import AccountService from '@/services/accountService';
import { useRoute, useRouter } from 'vue-router';
import { inject, ref, watch } from 'vue';

const accountService = inject('accountService') as AccountService;
const authStore = useAuthStore();
const router = useRouter();
const route = useRoute();
const returnPath = ref<string>(route.path);

watch(() => route.path, (newVal) => {
    if (!['/account/login', '/account/register'].includes(newVal)) {
        returnPath.value = newVal;
    }
});

const logout = async () => {
    await accountService.logout();
    await router.push({ name: 'Login', query: { returnUrl: returnPath.value } });
};
</script>

<template>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">RecipeApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <RouterLink class="nav-link text-dark" :to="{name: 'Home'}">Home</RouterLink>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Home/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Navigation
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <RouterLink class="dropdown-item" :to="{name: 'Samples'}">
                                        Samples
                                    </RouterLink>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <ul v-if="!authStore.isAuthenticated" class="navbar-nav">
                        <li class="nav-item">
                            <RouterLink class="nav-link text-dark"
                                        :to="{name: 'Register', query: {...route.query, returnUrl: returnPath}}">Register
                            </RouterLink>
                        </li>
                        <li class="nav-item">
                            <RouterLink class="nav-link text-dark"
                                        :to="{name: 'Login', query: {...route.query, returnUrl: returnPath}}">Login
                            </RouterLink>
                        </li>
                    </ul>
                    <ul v-else class="navbar-nav">
                        <li class="nav-item">
                            <RouterLink class="nav-link text-dark" :to="{}">
                                Hello, {{ authStore.username }}!
                            </RouterLink>
                        </li>
                        <li class="nav-item">
                            <button @click="logout" class="nav-link text-dark" type="button">
                                Logout
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
</template>

<style scoped>

</style>

// exam_webapp_react/src/components/Header.tsx
import Link from 'next/link';
import Identity from '@/components/Identity';

export default function Header() {
    return (
        <header>
            <nav
                className="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div className="container-fluid">
                    <Link href={'/'} className="navbar-brand">WebApp</Link>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul className="navbar-nav flex-grow-1">
                            <li className="nav-item">
                                <Link href={'/'} className="nav-link text-dark">Home</Link>
                            </li>
                            <li className="nav-item dropdown">
                                <a className="nav-link dropdown-toggle" href="#" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    Navigation
                                </a>
                                <ul className="dropdown-menu">
                                    <li>
                                        <Link className="dropdown-item" href={'/samples'}>Samples</Link>
                                    </li>
                                    <li>
                                        <hr className="dropdown-divider" />
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <ul className="navbar-nav">
                        <Identity />
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    );
}
