// frontend/recipe_app_react/src/app/ingredients/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { Ingredient } from '@/types';
import { useServices } from '@/components/ServiceContext';
import Link from 'next/link';

export default function Ingredients() {
    const [isLoading, setIsLoading] = useState(true);
    const [ingredients, setIngredients] = useState<Ingredient[]>([]);
    const { ingredientsService } = useServices();

    const loadIngredients = async () => {
        const allIngredients = await ingredientsService.findAll();
        if (allIngredients.data) {
            setIngredients(allIngredients.data);
        }
        setIsLoading(false);
    };

    useEffect(() => {
        loadIngredients().then();
    }, []);
    
    return (
        <>
            <h1>Index</h1>

            <p>
                <Link href={'/ingredients/create'}>Create New</Link>
            </p>
            {(isLoading)
                ? <p>Loading...</p>
                : renderIngredientsTable(ingredients)}
        </>
    );
}

function renderIngredientsTable(ingredients: Ingredient[]) {
    return <table className="table">
        <thead>
        <tr>
            <th>
                Name
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {renderIngredients(ingredients)}
        </tbody>
    </table>;
}

function renderIngredients(ingredients: Ingredient[]) {
    return ingredients.map(ingredient => (
        <tr key={ingredient.id}>
            <td>
                {ingredient.name}
            </td>
            <td>
                <Link href={`/ingredients/${ingredient.id}/edit`}>Edit</Link> |
                <Link href={`/ingredients/${ingredient.id}`}>Details</Link> |
                <Link href={`/ingredients/${ingredient.id}/delete`}>Delete</Link>
            </td>
        </tr>
    ));
}

// frontend/recipe_app_vue/src/views/ingredients/Ingredients.vue
<script setup lang="ts">
import type { Ingredient, ResultObject } from '@/types';
import { onMounted, ref } from 'vue';
import useServices from '@/helpers/useServices';

const { ingredientsService } = useServices();
const ingredients = ref<Ingredient[]>([]);

onMounted(async () => {
    const result = await ingredientsService.findAll();
    ingredients.value = result.data!;
});
</script>

<template>
    <h1>Ingredients</h1>
    <p>
        <RouterLink :to="{name: 'IngredientCreate'}">Create New</RouterLink>
    </p>
    <table v-if="ingredients.length" class="table">
        <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Types
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="ingredient in ingredients" :key="ingredient.id">
            <td>
                {{ ingredient.name }}
            </td>
            <td>
                {{ ingredient.ingredientTypeAssociations?.length }}
            </td>
            <td>
                <RouterLink :to="{name: 'IngredientEdit', params: {id: ingredient.id}}">Edit</RouterLink> |
                <RouterLink :to="{name: 'IngredientDetails', params: {id: ingredient.id}}">Details</RouterLink> |
                <RouterLink :to="{name: 'IngredientDelete', params: {id: ingredient.id}}">Delete</RouterLink>
            </td>
        </tr>
        </tbody>
    </table>
    <span v-else>Loading...</span>
</template>

<style scoped></style>
