// frontend/recipe_app_react/src/app/ingredient-types/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { IngredientType } from '@/types';
import { useServices } from '@/components/ServiceContext';
import Link from 'next/link';

export default function IngredientTypes() {
    const [isLoading, setIsLoading] = useState(true);
    const [ingredientTypes, setIngredientTypes] = useState<IngredientType[]>([]);
    const { ingredientTypesService } = useServices();

    const loadIngredientTypes = async () => {
        const allIngredientTypes = await ingredientTypesService.findAll();
        if (allIngredientTypes.data) {
            setIngredientTypes(allIngredientTypes.data);
        }
        setIsLoading(false);
    };

    useEffect(() => {
        loadIngredientTypes().then();
    }, []);

    return (
        <>
            <h1>Index</h1>

            <p>
                <Link href={'/ingredient-types/create'}>Create New</Link>
            </p>
            {(isLoading)
                ? <p>Loading...</p>
                : renderIngredientTypesTable(ingredientTypes)}
        </>
    );
}

function renderIngredientTypesTable(ingredientTypes: IngredientType[]) {
    return <table className="table">
        <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {renderIngredientTypes(ingredientTypes)}
        </tbody>
    </table>;
}

function renderIngredientTypes(ingredientTypes: IngredientType[]) {
    return ingredientTypes.map(type => (
        <tr key={type.id}>
            <td>
                {type.name}
            </td>
            <td>
                {type.description}
            </td>
            <td>
                <Link href={`/ingredient-types/${type.id}/edit`}>Edit</Link> |
                <Link href={`/ingredient-types/${type.id}`}>Details</Link> |
                <Link href={`/ingredient-types/${type.id}/delete`}>Delete</Link>
            </td>
        </tr>
    ));
}

// recipe-app-frontend/src/views/ingredient-types/IngredientTypes.vue
<script setup lang="ts">
import type { IngredientType } from '@/types';
import { onMounted, ref } from 'vue';
import useServices from '@/helpers/useServices';

const { ingredientTypesService } = useServices();

const ingredientTypes = ref<IngredientType[]>([]);

onMounted(async () => {
    const result = await ingredientTypesService.findAll();
    ingredientTypes.value = result.data!;
});
</script>

<template>
    <h1>Ingredient types</h1>
    <p>
        <RouterLink :to="{name: 'IngredientTypeCreate'}">Create New</RouterLink>
    </p>
    <table v-if="ingredientTypes.length" class="table">
        <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="type in ingredientTypes" :key="type.id">
            <td>
                {{ type.name }}
            </td>
            <td>
                {{ type.description }}
            </td>
            <td>
                <RouterLink :to="{name: 'IngredientTypeEdit', params: {id: type.id}}">Edit</RouterLink> |
                <RouterLink :to="{name: 'IngredientTypeDetails', params: {id: type.id}}">Details</RouterLink> |
                <RouterLink :to="{name: 'IngredientTypeDelete', params: {id: type.id}}">Delete</RouterLink>
            </td>
        </tr>
        </tbody>
    </table>
    <span v-else>Loading...</span>
</template>

<style scoped></style>
